function data() { var json = { "name": "EventListener","children": [{ "name": "ArgoEventListener","children": [{ "name": "ArgoGeneratorEventListener","children": [{ "name": "LanguageComboBox"},
{ "name": "TArgoGeneratorEventListener"},
]},
{ "name": "ArgoHelpEventListener","children": [{ "name": "ArgoStatusBar"},
{ "name": "HelpListener"},
{ "name": "TArgoHelpEventListener"},
]},
{ "name": "ArgoStatusEventListener","children": [{ "name": "ArgoStatusBar"},
{ "name": "TArgoStatusEventListener"},
]},
{ "name": "ArgoProfileEventListener","children": [{ "name": "ProfileChangeListener"},
{ "name": "TArgoProfileEventListener"},
]},
{ "name": "ArgoNotationEventListener","children": [{ "name": "NotationComboBox"},
{ "name": "FigNodeModelElement","children": [{ "name": "ShadowFig"},
{ "name": "FigStateVertex","children": [{ "name": "FigActionState","children": [{ "name": "FigCallState"},
]},
{ "name": "FigSubactivityState"},
{ "name": "FigSynchState"},
{ "name": "FigState","children": [{ "name": "FigConcurrentRegion"},
{ "name": "FigSimpleState"},
{ "name": "FigCompositeState"},
{ "name": "FigSubmachineState"},
]},
{ "name": "FigJunctionState"},
{ "name": "FigHistoryState","children": [{ "name": "FigShallowHistoryState"},
{ "name": "FigDeepHistoryState"},
]},
{ "name": "FigBranchState"},
{ "name": "FigFinalState"},
{ "name": "FigJoinState"},
{ "name": "FigStubState"},
{ "name": "FigForkState"},
{ "name": "FigInitialState"},
]},
{ "name": "FigPartition"},
{ "name": "FigPool"},
{ "name": "FigObjectFlowState"},
{ "name": "FigClassifierRole"},
{ "name": "AbstractFigNode","children": [{ "name": "FigMNode"},
{ "name": "FigNodeInstance"},
]},
{ "name": "AbstractFigComponent","children": [{ "name": "FigComponent"},
{ "name": "FigComponentInstance"},
]},
{ "name": "FigObject"},
{ "name": "FigVertex"},
{ "name": "FigCompartmentBox","children": [{ "name": "FigClassifierBox","children": [{ "name": "FigInterface"},
{ "name": "FigDataType","children": [{ "name": "FigEnumeration"},
]},
{ "name": "FigSignal","children": [{ "name": "FigException"},
]},
{ "name": "FigClass","children": [{ "name": "FigClassAssociationClass"},
]},
]},
{ "name": "FigStereotypeDeclaration"},
{ "name": "FigUseCase"},
]},
{ "name": "FigPackage","children": [{ "name": "FigModel"},
{ "name": "FigSubsystem"},
]},
{ "name": "FigComment"},
{ "name": "FigNodeAssociation"},
{ "name": "FigMessage"},
{ "name": "FigEdgePort"},
{ "name": "FigActor"},
{ "name": "FigNode"},
{ "name": "FigPort"},
{ "name": "FigClassifierRole"},
{ "name": "FigCircleState","children": [{ "name": "FigExitPoint"},
{ "name": "FigEntryPoint"},
]},
{ "name": "FigVertex"},
]},
{ "name": "ArgoDiagram","children": [{ "name": "SequenceDiagram","children": [{ "name": "UMLSequenceDiagram"},
]},
{ "name": "ArgoDiagramImpl","children": [{ "name": "UMLDiagram","children": [{ "name": "UMLActivityDiagram"},
{ "name": "UMLCollaborationDiagram"},
{ "name": "UMLDeploymentDiagram"},
{ "name": "UMLStateDiagram"},
{ "name": "UMLClassDiagram"},
{ "name": "UMLUseCaseDiagram"},
{ "name": "BaseDiagram","children": [{ "name": "UMLActivityDiagram"},
]},
{ "name": "UMLDeploymentDiagram"},
{ "name": "UMLSequenceDiagram"},
{ "name": "UMLStateDiagram"},
]},
{ "name": "TestTargetManager$1"},
]},
]},
{ "name": "FigEdgeModelElement","children": [{ "name": "FigAssociation","children": [{ "name": "FigAssociationRole"},
{ "name": "FigAssociationClass"},
]},
{ "name": "FigTransition"},
{ "name": "FigLink"},
{ "name": "FigDependency","children": [{ "name": "FigUsage"},
{ "name": "FigPermission"},
{ "name": "FigAbstraction"},
]},
{ "name": "FigGeneralization"},
{ "name": "FigEdgeAssociationClass"},
{ "name": "FigAssociationEnd"},
{ "name": "FigExtend"},
{ "name": "FigInclude"},
{ "name": "FigMessage"},
]},
{ "name": "FigSingleLineTextWithNotation","children": [{ "name": "CompartmentFigText","children": [{ "name": "FigFeature","children": [{ "name": "FigOperation"},
{ "name": "FigAttribute"},
]},
{ "name": "FigEnumerationLiteral"},
{ "name": "FigExtensionPoint"},
]},
{ "name": "FigMultiplicity"},
{ "name": "FigRole"},
]},
{ "name": "TArgoNotationEventListener"},
{ "name": "EventCatcher"},
]},
{ "name": "ArgoDiagramAppearanceEventListener","children": [{ "name": "FigNodeModelElement","children": [{ "name": "ShadowFig"},
{ "name": "FigStateVertex","children": [{ "name": "FigActionState","children": [{ "name": "FigCallState"},
]},
{ "name": "FigSubactivityState"},
{ "name": "FigSynchState"},
{ "name": "FigState","children": [{ "name": "FigConcurrentRegion"},
{ "name": "FigSimpleState"},
{ "name": "FigCompositeState"},
{ "name": "FigSubmachineState"},
]},
{ "name": "FigJunctionState"},
{ "name": "FigHistoryState","children": [{ "name": "FigShallowHistoryState"},
{ "name": "FigDeepHistoryState"},
]},
{ "name": "FigBranchState"},
{ "name": "FigFinalState"},
{ "name": "FigJoinState"},
{ "name": "FigStubState"},
{ "name": "FigForkState"},
{ "name": "FigInitialState"},
]},
{ "name": "FigPartition"},
{ "name": "FigPool"},
{ "name": "FigObjectFlowState"},
{ "name": "FigClassifierRole"},
{ "name": "AbstractFigNode","children": [{ "name": "FigMNode"},
{ "name": "FigNodeInstance"},
]},
{ "name": "AbstractFigComponent","children": [{ "name": "FigComponent"},
{ "name": "FigComponentInstance"},
]},
{ "name": "FigObject"},
{ "name": "FigVertex"},
{ "name": "FigCompartmentBox","children": [{ "name": "FigClassifierBox","children": [{ "name": "FigInterface"},
{ "name": "FigDataType","children": [{ "name": "FigEnumeration"},
]},
{ "name": "FigSignal","children": [{ "name": "FigException"},
]},
{ "name": "FigClass","children": [{ "name": "FigClassAssociationClass"},
]},
]},
{ "name": "FigStereotypeDeclaration"},
{ "name": "FigUseCase"},
]},
{ "name": "FigPackage","children": [{ "name": "FigModel"},
{ "name": "FigSubsystem"},
]},
{ "name": "FigComment"},
{ "name": "FigNodeAssociation"},
{ "name": "FigMessage"},
{ "name": "FigEdgePort"},
{ "name": "FigActor"},
{ "name": "FigNode"},
{ "name": "FigPort"},
{ "name": "FigClassifierRole"},
{ "name": "FigCircleState","children": [{ "name": "FigExitPoint"},
{ "name": "FigEntryPoint"},
]},
{ "name": "FigVertex"},
]},
{ "name": "ArgoDiagram","children": [{ "name": "SequenceDiagram","children": [{ "name": "UMLSequenceDiagram"},
]},
{ "name": "ArgoDiagramImpl","children": [{ "name": "UMLDiagram","children": [{ "name": "UMLActivityDiagram"},
{ "name": "UMLCollaborationDiagram"},
{ "name": "UMLDeploymentDiagram"},
{ "name": "UMLStateDiagram"},
{ "name": "UMLClassDiagram"},
{ "name": "UMLUseCaseDiagram"},
{ "name": "BaseDiagram","children": [{ "name": "UMLActivityDiagram"},
]},
{ "name": "UMLDeploymentDiagram"},
{ "name": "UMLSequenceDiagram"},
{ "name": "UMLStateDiagram"},
]},
{ "name": "TestTargetManager$1"},
]},
]},
{ "name": "FigEdgeModelElement","children": [{ "name": "FigAssociation","children": [{ "name": "FigAssociationRole"},
{ "name": "FigAssociationClass"},
]},
{ "name": "FigTransition"},
{ "name": "FigLink"},
{ "name": "FigDependency","children": [{ "name": "FigUsage"},
{ "name": "FigPermission"},
{ "name": "FigAbstraction"},
]},
{ "name": "FigGeneralization"},
{ "name": "FigEdgeAssociationClass"},
{ "name": "FigAssociationEnd"},
{ "name": "FigExtend"},
{ "name": "FigInclude"},
{ "name": "FigMessage"},
]},
{ "name": "TArgoDiagramAppearanceEventListener"},
{ "name": "EventCatcher"},
]},
]},
{ "name": "ToDoListListener","children": [{ "name": "ToDoByType"},
{ "name": "ToDoByPriority"},
{ "name": "ToDoByOffender"},
{ "name": "ToDoByGoal"},
{ "name": "ToDoByPoster"},
{ "name": "ToDoByDecision"},
{ "name": "ToDoPane"},
]},
{ "name": "TargetListener","children": [{ "name": "TabTarget","children": [{ "name": "TabModelTarget","children": [{ "name": "TabChecklist"},
{ "name": "TabText","children": [{ "name": "TabSrc"},
]},
{ "name": "PropPanelDiagram","children": [{ "name": "PropPanelUMLActivityDiagram"},
{ "name": "PropPanelUMLCollaborationDiagram"},
{ "name": "PropPanelUMLDeploymentDiagram"},
{ "name": "PropPanelUMLStateDiagram"},
{ "name": "PropPanelUMLClassDiagram"},
{ "name": "PropPanelUMLUseCaseDiagram"},
{ "name": "PropPanelUMLActivityDiagram"},
{ "name": "PropPanelUMLDeploymentDiagram"},
{ "name": "PropPanelUMLSequenceDiagram"},
{ "name": "PropPanelUMLStateDiagram"},
]},
{ "name": "PropPanelString"},
{ "name": "TabDiagram"},
{ "name": "TabDocumentation"},
{ "name": "TabConstraints"},
{ "name": "TabTaggedValues"},
{ "name": "TabStereotype"},
{ "name": "TabProps"},
]},
{ "name": "TabFigTarget","children": [{ "name": "StylePanel","children": [{ "name": "StylePanelFig","children": [{ "name": "StylePanelFigRRect"},
{ "name": "StylePanelFigText"},
{ "name": "StylePanelFigNodeModelElement","children": [{ "name": "StylePanelFigPackage"},
{ "name": "StylePanelFigClass"},
{ "name": "StylePanelFigInterface"},
{ "name": "StylePanelFigAssociationClass"},
{ "name": "StylePanelFigMessage"},
{ "name": "StylePanelFigUseCase"},
]},
{ "name": "SPFigEdgeModelElement"},
]},
{ "name": "MockStylePanel"},
]},
{ "name": "TabStyle"},
]},
]},
{ "name": "TabToDoTarget","children": [{ "name": "WizStep","children": [{ "name": "WizStepTextField"},
{ "name": "WizStepConfirm"},
{ "name": "WizDescription"},
{ "name": "WizStepCue"},
{ "name": "WizStepChoice"},
{ "name": "WizStepManyTextFields"},
]},
{ "name": "TabToDo"},
]},
{ "name": "GenericArgoMenuBar","children": [{ "name": "MenuBar2"},
{ "name": "MenuBar14"},
]},
{ "name": "MultiEditorPane"},
{ "name": "DetailsPane"},
{ "name": "ProjectActions"},
{ "name": "ProjectBrowser"},
{ "name": "ExplorerTargetListener"},
{ "name": "HistoryManager"},
{ "name": "ButtonActionNewEvent","children": [{ "name": "ButtonActionNewTimeEvent"},
{ "name": "ButtonActionNewSignalEvent"},
{ "name": "ButtonActionNewChangeEvent"},
{ "name": "ButtonActionNewCallEvent"},
]},
{ "name": "ActionAddExtensionPoint$1"},
{ "name": "DiagramNameDocument"},
{ "name": "UMLComboBoxModel2","children": [{ "name": "UMLDiagramHomeModelComboBoxModel"},
{ "name": "UMLTagDefinitionComboBoxModel"},
]},
{ "name": "AbstractActionNavigate","children": [{ "name": "ActionNavigateUpFromDiagram"},
{ "name": "ActionNavigateOwner"},
{ "name": "ActionNavigateContainerElement"},
{ "name": "ActionNavigateAction"},
{ "name": "ActionNavigateUpNextDown"},
{ "name": "ActionNavigateAssociation"},
{ "name": "ActionNavigateOppositeAssocEnd"},
{ "name": "ActionNavigateUpPreviousDown"},
{ "name": "ActionNavigateContext"},
{ "name": "ActionNavigateNamespace"},
{ "name": "ActionNavigateTransition"},
]},
{ "name": "ActionAddMessage$1"},
{ "name": "UMLStereotypeListModel","children": [{ "name": "UMLModelElementStereotypeListModel"},
{ "name": "UMLModelStereotypeListModel"},
]},
{ "name": "ActionDeleteModelElements$1"},
{ "name": "UMLModelElementListModel2","children": [{ "name": "UMLStereotypeTagDefinitionListModel"},
{ "name": "UMLExtensionPointExtendListModel"},
{ "name": "UMLStateMachineContextListModel"},
]},
{ "name": "UMLDocument","children": [{ "name": "UMLModelElementTaggedValueProxy"},
{ "name": "UMLPlainTextDocument","children": [{ "name": "UMLModelElementCommentDocument"},
{ "name": "UMLModelElementTaggedValueDocument"},
{ "name": "UMLReceptionSpecificationDocument"},
{ "name": "UMLSynchStateBoundDocument"},
{ "name": "UMLExtensionPointLocationDocument"},
{ "name": "UMLOperationSpecificationDocument"},
{ "name": "UMLDiagramNameDocument"},
{ "name": "UMLModelElementNameDocument"},
{ "name": "UMLDiscriminatorNameDocument"},
{ "name": "UMLReceptionSpecificationDocument"},
{ "name": "GenericUMLPlainTextDocument"},
]},
]},
{ "name": "UMLExpressionModel2","children": [{ "name": "UMLExpressionExpressionModel"},
{ "name": "UMLScriptExpressionModel"},
{ "name": "UMLRecurrenceExpressionModel"},
{ "name": "UMLConditionExpressionModel"},
{ "name": "UMLTimeExpressionModel"},
{ "name": "UMLChangeExpressionModel"},
]},
{ "name": "UMLCheckBox2","children": [{ "name": "UMLTaggedValueCheckBox","children": [{ "name": "UMLDeprecatedCheckBox"},
{ "name": "UMLDerivedCheckBox"},
]},
{ "name": "UMLActionSynchCheckBox"},
{ "name": "UMLActionAsynchronousCheckBox"},
{ "name": "UMLGeneralizableElementLeafCheckBox"},
{ "name": "UMLAssociationEndTargetScopeCheckbox"},
{ "name": "UMLAssociationEndOrderingCheckBox"},
{ "name": "UMLGeneralizableElementAbstractCheckBox"},
{ "name": "UMLStructuralFeatureTargetScopeCheckBox"},
{ "name": "UMLFeatureOwnerScopeCheckBox"},
{ "name": "UMLClassActiveCheckBox"},
{ "name": "UMLBehavioralFeatureQueryCheckBox"},
{ "name": "UMLAssociationEndNavigableCheckBox"},
{ "name": "UMLGeneralizableElementRootCheckBox"},
]},
{ "name": "UMLRadioButtonPanel","children": [{ "name": "UMLParameterDirectionKindRadioButtonPanel"},
{ "name": "UMLAssociationEndChangeabilityRadioButtonPanel"},
{ "name": "UMLOperationConcurrencyRadioButtonPanel"},
{ "name": "UMLModelElementVisibilityRadioButtonPanel"},
{ "name": "UMLStructuralFeatureChangeabilityRadioButtonPanel"},
]},
{ "name": "UMLComboBox2","children": [{ "name": "UMLEditableComboBox","children": [{ "name": "UMLSearchableComboBox"},
]},
]},
{ "name": "ActionAddAttribute$1"},
{ "name": "ActionAddOperation$1"},
{ "name": "TestTargetListener"},
{ "name": "Listener"},
{ "name": "MyListener"},
]},
{ "name": "ProgressListener","children": [{ "name": "ProgressMgr"},
{ "name": "ProgressMonitor","children": [{ "name": "ProgressMonitorWindow"},
{ "name": "SplashScreen"},
{ "name": "StatusBar","children": [{ "name": "ArgoStatusBar"},
]},
{ "name": "ImportStatusScreen"},
]},
]},
{ "name": "ShortcutChangedListener","children": [{ "name": "SettingsTabShortcuts"},
]},
{ "name": "UmlChangeListener","children": [{ "name": "AssociationChangeListener","children": [{ "name": "FigCompartment","children": [{ "name": "FigNameCompartment"},
]},
]},
]},
]}; return json; }
