function data() { var json = { "name": "ROOT", "children": [
{ "name": "String"},
{ "name": "NullProgressMonitor"},
{ "name": "Object","children": [{ "name": "JiraCrawler"},
{ "name": "BugTrackerUser"},
{ "name": "BugzillaCrawler"},
{ "name": "BugzillaXMLParser"},
{ "name": "BugzillaXMLParser$1"},
{ "name": "BugInfo"},
{ "name": "Environment"},
{ "name": "Declaration"},
{ "name": "LanguageFactory"},
{ "name": "LanguageDefinition"},
{ "name": "RepositoryCrawler"},
{ "name": "JavaASTGenerator"},
]},
{ "name": "Issue"},
{ "name": "SearchResult"},
{ "name": "List"},
{ "name": "URI"},
{ "name": "AnonymousAuthenticationHandler"},
{ "name": "URISyntaxException"},
{ "name": "User"},
{ "name": "JerseyJiraRestClientFactory"},
]}; return json; }
